select TREE.PLT_CN, TREE.CN as "TREE_CN", TPA_UNADJ, STATUSCD, TREECLCD, STANDING_DEAD_CD, VOLCFSND, COND.INVYR, COND_STATUS_CD, STANDING_DEAD_CD as TREE_COND
from COND
INNER JOIN TREE ON COND.PLT_CN = TREE.PLT_CN
WHERE COND.INVYR >= {start_year} AND COND.INVYR <= {end_year} AND TREE.PLT_CN in ({id_list*})