---
params:
  eval_type: 
  raster_name:
  zone_num: 
  eval_vars: 
  cms_path: 
title: "TreeMap Zonal Validation: Zone `r params$zone_num` "
subtitle: "`r params$raster_name` ; `r params$eval_type`"
output:
  word_document: default
  html_document:
    df_print: paged
  pdf_document: default
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}

library(flextable)
library(knitr)
# set chunk options
knitr::opts_chunk$set(echo = FALSE)

```

Landfire zone: `r params$zone_num`

Run name: `r params$raster_name` 

Variables to evaluate: `r params$eval_type`

Path for confusion matrices: `r params$cms_path`

Unique plots imputed in zone: `r length(freq(raw_imputed_raster)$value)`

Plots available in zone: `r nrow(plot.df)`

Percent of available plots imputed: `r round(100*( length(freq(raw_imputed_raster)$value) / nrow(plot.df)), 2)`

```{r plot raster}
# plot raster 
plot(raw_imputed_raster, main = glue::glue("Raw Imputation: Zone {params$zone_num}"))
```


```{r format and plot tables for each var, results = 'asis', warning = F}
for(v in 1:length(eval_vars)){

  var_in <- eval_vars[v]
  
  cat("\n\n\\pagebreak\n")
  print(glue("**Variable: {var_in}**
  
             "))
  
  ##### LOOP OVER EACH VAR
  
  cms <- cms_all[[var_in]]
  
  if(var_in == "evt_gp"){
    names(cms$classes)[2:(nrow(evg_reclass)+1)]<- evg_reclass$EVT_GP
    cms$freq$class<- evg_reclass$EVT_GP
    cms$freq_norm$class<- evg_reclass$EVT_GP
    #
    rownames(cms$raw)[1:nrow(evg_reclass)]<- evg_reclass$EVT_GP
    colnames(cms$raw)[1:nrow(evg_reclass)]<- evg_reclass$EVT_GP
    
    }
  
  
  # Initial Table formatting
  ###################################################################################
  
  # Prep frequency table
  #---------------------------------------------#
  
  freq <-
    cms$freq %>%
    #select fields of interest
    dplyr::select(class, ref, pred) %>%
    dplyr::mutate(class = factor(class))
  
  n_classes <- nrow(freq)
  
  # Calculate normalized frequency table 
  #--------------------------------------------#
  # calc total to use in normalizing
  total_pred = sum(freq$pred)
  total_ref = sum(freq$ref)
  
  # add normalized frequency
  freq_norm <- freq %>%
    mutate(pred = pred/total_pred, 
           ref = ref/total_ref)
    # Work with reference data and join to normalized frequency
  rat_z<- plot.df
  
  # Rename ID to PLOTID
  #rat_z %<>% rename("PLOTID" = "ID")
  
  # Calc frequency for all vars in RAT
  #------------------------------------------#
  
  rat_freq_all <- list()

  # get frequency table
  f_out <- rat_z %>%
    select(all_of(var_in)) %>%
    table() %>%
    data.frame() 
  
  # add normalized frequency
  f_out$Freq_norm = f_out$Freq/sum(f_out$Freq)
  
  # join with other outputs
  rat_freq_all = c(rat_freq_all, list(f_out))
  
  
  # Join normalized frequency table with reference
  #----------------------------------------------#
  rat_freq <- f_out
  
  #prep rat frequency table
  rat_freq %<>% 
    rename(class = !!var_in, 
           "aRAT" = Freq_norm) %>%
    select(-Freq)
  
  # join
  freq_norm %<>%
    full_join(rat_freq, by = join_by("class")) %>%
    arrange(class)
  
  # Prep CM Classes
  #---------------------------------------------#
  
  # get single cm for classes
  cm_classes <- cms$classes
  
  #manipulate
  cm_classes %<>%
    pivot_longer(!metric, names_to = "class") %>%
    mutate(class = factor(class)) %>%
    mutate(value = round(value, round_dig))
  
  # get number of classes
  nclass = length(unique(cm_classes$class))
  
  # Prep raw CM
  #------------------------------------------------#
  
  #load cm_raw table
  cm_raw <- as.data.frame.matrix(cms$raw)
  
  # Prep cm overall metrics table
  #------------------------------------------------------#
  
  cm_overall <- cms$overall
  
  #format
  cm_overall %<>% 
    mutate(value = round(value, round_dig))
  
  row.names(cm_overall) <- NULL
  
  # Plotting
  ##################################################################################
  
  # Bar plot: Raw frequency, observed vs. predicted for each class 
  # ---------------------------------------------------------#
  
  #format frequency table for plotting
  freq_t1 <- freq %>%
    pivot_longer(!class, names_to = "dataset") %>%
    dplyr::rename(frequency = "value") %>%
    arrange(dataset, class)
  
  #plot
  barchart1 <- freq_t1 %>%
    ggplot() +
    geom_col(aes(x = class, y = frequency, fill = factor(dataset)), position = "dodge") +
    scale_fill_manual(name = "Dataset", labels = plot_labels,values = c("aquamarine3", "chartreuse4"))+
    theme_bw() +
    ggtitle(glue("Frequency of classes
            Zone: z{zone_num} ; Attribute: {var_in}"))
  
  # conditionally flip axis text labeling
  if(var_in == "EVT_GP") {
    barchart1 <- barchart1 + 
      theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
  }

  
  # Bar plot: Normalized frequency, observed vs. predicted vs. for each class 
  # ---------------------------------------------------------#
  
  #format frequency table for plotting
  freq_t2 <- freq_norm %>%
    pivot_longer(!class, names_to = "dataset") %>%
    dplyr::rename(frequency = "value") %>%
    mutate(dataset= factor(dataset)) %>%
    arrange(dataset, class)
  
  #plot
  barchart2 <- freq_t2 %>%
    ggplot() +
    geom_col(aes(x = class, y = frequency, fill = factor(dataset)), position = "dodge") +
    scale_fill_manual(name = "Dataset", labels = c("Ground (FIA)", plot_labels),values = c("springgreen4", "aquamarine3", "chartreuse4"))+
    theme_bw() +
    ggtitle(glue("Normalized frequency of classes
            Zone: z{zone_num} ; Attribute: {var_in}"))
  
  # conditionally flip axis text labeling
  if(var_in == "EVT_GP") {
    barchart2 <- barchart2 + 
      theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
  }
  
  # Scatterplot: N of class in reference data vs. classwise accuracy
  # -----------------------------------------------------------------#
  
  # get accuracy for each class
  acc <- cm_classes %>%
    filter(metric == "Balanced Accuracy")
  
  n_acc <- plot.df %>%
    select(plt_cn, ID, !!var_in) %>%
    rename("class" = !!var_in) %>%
    mutate(class = factor(class)) %>%
    group_by(class) %>%
    summarize(n = n()) %>%
    left_join(acc, by = "class")

  
  # plot
  scatter_plot1 <- n_acc %>%
    ggplot()+
    geom_point(aes(x = n, y = value), size = 2) + 
    theme_bw() +
    labs(x = "total N of class in reference data", y = "Balanced Accuracy") + 
    ggtitle(glue("Accuracy vs. n Reference pts per class
            Zone: z{zone_num} ; Attribute: {var_in}"))
  
  
  # Scatterplot: Total obs of class vs. classwise accuracy
  # -----------------------------------------------------------------#
  
  # get accuracy for each class
  acc <- cm_classes %>%
    filter(metric == "Balanced Accuracy")
  
  # join with total N for each class
  freq_acc <- freq %>%
    #select(-X) %>%
    #rename("class" = value) %>%
    group_by(class) %>%
    summarise(n = ref + pred) %>%
    left_join(acc, by = "class")
  
  # plot
  scatter_plot2 <- freq_acc %>%
    ggplot()+
    geom_point(aes(x = n, y = value), size = 2) + 
    theme_bw() +
    labs(x = "total N of class in Imputed observations", y = "Balanced Accuracy") + 
    ggtitle(glue("Accuracy vs. N Imputed Obs per class
            Zone: z{zone_num} ; Attribute: {var_in}"))
  
  
  # Prep confusion matrix for display
  # -------------------------------------------------#
  
  #get overall accuracy 
  oa <- cm_overall %>%
    filter(metric == "Accuracy") %>%
    select(value) 
  
  if (var_in != "disturb_code"){
    print(glue::glue("*Overall accuracy: {round(oa*100,4)}%*
                   
                  "))
  }
  
  
  oa %<>%
    round(round_dig)
  
  if (var_in == "disturb_code"){
    cms_adjusted<- matrix(nrow=2,ncol=2)
    cms_adjusted[1,1]<- cms$raw[1,1]
    cms_adjusted[1,2]<- cms$raw[1,2] + cms$raw[1,3]
    #
    cms_adjusted[2,2]<- cms$raw[2,2] + cms$raw[3,3] + cms$raw[2,3] + cms$raw[3,2]
    cms_adjusted[2,1]<- cms$raw[2,1] + cms$raw[3,1]
    #
    adjusted_accuracy<- (cms_adjusted[1,1] + cms_adjusted[2,2]) / (cms_adjusted[1,1] + cms_adjusted[2,2] +
                                                                     cms_adjusted[2,1] + cms_adjusted[1,2]) 
    
     print(glue::glue("*Overall accuracy: {round(oa*100,4)}%*  /  *Adjusted overall accuracy: {round(round(adjusted_accuracy,4)*100,4)}%*
                   
                   "))
    
  }
    

    print(barchart1)
    print(barchart2)
    print(scatter_plot1)
    print(scatter_plot2)
  
  
  # get producer's accuracy for each class - precision
  pa <- cm_classes %>%
    filter(metric == "Precision") %>%
    mutate(value = round(value, round_dig))  %>%
    select(value) %>%
    # replace NA with character
    mutate(value = as.character(value)) %>%
    replace_na(list(value = "NA")) %>%
    #rename
    rename("Prod. Acc" = value) %>%
    # add extra row to be able to bind
    rbind(c("NA"))
  
  # get user's accuracy for each class - recall
  ua <- cm_classes %>%
    filter(metric == "Recall") %>% 
    mutate(value = round(value, round_dig))  %>%
    select(value) %>%
    # replace NA with character
    mutate(value = as.character(value)) %>%
    replace_na(list(value = "NA")) 
  
  # join producer's accuracy
  cm_display <- cbind(cm_raw, pa)
  
  #format user's accuracy to be able to bind
  # create list of length that will make it match size of cm_display
  b <- data.frame(value = rep("NA", ncol(cm_display)- nrow(ua)))
  ua <- 
    #c("User's Acc") %>%
    rbind(ua, b) %>%
    # rename
    rename("User's Acc" = value) %>%
    t() %>%
    data.frame()
  
  # add names to ua be able to bind
  names(ua) <- names(cm_display)
  
  #bind ua with cm
  cm_display <- rbind(cm_display, ua)
  
  # make row names a column
  cm_display$Predicted <- row.names(cm_display)
  row.names(cm_display) <- NULL
  
  # bind row name column back with df
  cm_display <- cbind(Predicted = cm_display$Predicted, cm_display[1:ncol(cm_display)-1])
  
  
  
  # flextable formatting for cm
  
  ### NOTE: column and row number selections are hard coded (based on canopy height) in formatting section
  
  table_cm <- flextable(cm_display) %>%
    # add header and footer
    add_header_row(values = c("", "Reference"), colwidths = c(1, ncol(cm_display)-1)) %>%
    add_footer_row(values = c("Overall accuracy", oa), colwidths = c(ncol(cm_display)-1, 1)) %>%
    # add background color for producer's and user's acc rows
    bg(i = 1:nclass, j = nclass+3, bg = "darkseagreen1") %>%
    bg(i = nclass+2, j = 1:nclass+1, bg = "darkseagreen1") %>%
    # bold text
    style(i = -1:nclass+2, j = c(1,nclass+3), fp_text_default(bold = TRUE)) %>%
    style(i = nclass+2, j = 1:nclass+2, fp_text_default(bold = TRUE)) %>%
    bold(part = "header") %>%
    bold(part = "footer") %>%
    # add background color for overall accuracy
    bg(j = nclass + 3,  bg = "green4", part = "footer")%>%
    # make font smaller
    fontsize(size = 8, part = "all") %>%
    # add borders to body cells
    surround(border = fp_border_default(color = "gray", width = 1), part = "body") %>%
    # add title
    set_caption(glue("Confusion Matrix  
             Zone: z{zone_num} ; Attribute: {var_in},
             {plot_labels}")) 
  # highlight diagonal values
  for (r in 1:(nrow(cm_display)-1)) {
    table_cm %<>%
      surround(i = r, j = r+1, border = fp_border_default(color = "cornflowerblue", width = 1.5), part = "body")
  }
  # fit to page
  
  table_cm <- FitFlextableToPage(ft = table_cm, 
                                 pgwidth = 7)
  
  
  #flextable_to_rmd(table_cm)
  cat(knitr::knit_print(table_cm))
  
  # End loop
}
```
